version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env    

volumes:
  postgres_data:
